### ISSUE TITLE
Usage with NodeOS

### ISSUE THREAD

**Issue by piranna** [Captainarash/CaptCC#1]
Nice approach! :-D I like how you have splitted each one of the steps in a different file and function :-) Maybe it could be converted to use Streams instead, but that's a different issue :-P

I was looking for a C compiler written in Javascript to be used on [NodeOS](http://node-os.com/), and maybe yours could be a good deal. What's the actual status of the project? Seems it's not possible to convert the assembly code to machine code yet, isn't it? Have you tried to use your compiler with external libraries (`printf()` on stdlib and so...)? And run it as a Node.js executable? Having each stage isolated, have you though about adding a processor that generates wasm assembly code too? :-)

**Comment by Captainarash** [comment]
Thank you!
This project is still in its baby steps and there is a lot more to be done. I'm single handed and it takes time to finish it. This is only the core functionality. Later I have to wrap it ti Node.js most probably. Also a compiler only generates the assembly code. Generating the machine opcodes is the linker&loader's job and I can't make that happen, at least not yet. You're completely welcome to contribute to this project. I need more brains and hands for this :D 
There are some things we need to complete for the core for now:
1. processing every possible correct syntax
2. compiling every function, structure and statement, etc but only without linking (no libraries :( ).
3. There is an issue with calling conventions in the code. I mixed 32-bit and 64-bit calling conventions. 
4. Add support for target architecture
5. Then finally adding the C standard library

If all these are done, then we launch it with Node.js
Any good?
